from datetime import timedelta

from django.db.models import QuerySet

from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .models import Notification, NotificationPreference
from .permissions import IsNotificationOwner
from .serializers import NotificationPreferenceSerializer, NotificationSerializer
from rest_framework.generics import (RetrieveUpdateAPIView)




class NotificationViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API for authenticated users to access their own notifications.

    Notifications are generated by backend services.

    Supported operations:

        GET    /notifications/
        GET    /notifications/{id}/
        GET    /notifications/unread/
        POST   /notifications/{id}/mark-read/
        POST   /notifications/{id}/mark-unread/
        POST   /notifications/mark-all-read/
        DELETE /notifications/{id}/
    """

    serializer_class = NotificationSerializer

    permission_classes = [
        IsAuthenticated,
        IsNotificationOwner,
    ]

    http_method_names = [
        "get",
        "post",
        "delete",
        "head",
        "options",
    ]

    def get_queryset(self) -> QuerySet:
        """
        Return only notifications belonging to the authenticated user
        and their company.
        """

        user = self.request.user

        if not user.is_authenticated:
            return Notification.objects.none()

        company = getattr(
            user,
            "company",
            None,
        )

        if company is None:
            return Notification.objects.none()

        return (
            Notification.objects
            .filter(
                recipient=user,
                company=company,
            )
            .select_related(
                "recipient",
                "company",
                "branch",
            )
        )

    @action(detail=False, methods=["get"], url_path="security-digest")
    def security_digest(self, request):
        """
        On-demand digest endpoint for superusers.
        Example: /api/notifications/security-digest?cadence=daily
        """
        user = request.user
        if not user.is_superuser:
            return Response(
                {"detail": "Only superusers can access the security digest."},
                status=status.HTTP_403_FORBIDDEN,
            )

        cadence = request.query_params.get("cadence", "DAILY").upper()
        now = timezone.now()

        if cadence == "DAILY":
            since = now - timedelta(hours=24)
        elif cadence == "WEEKLY":
            since = now - timedelta(days=7)
        else:
            return Response(
                {"detail": "Unsupported cadence. Use DAILY or WEEKLY."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        events = Notification.objects.filter(
            notification_type="SECURITY",
            created_at__gte=since
        ).order_by("created_at")

        digest_lines = [
            {
                "title": n.title,
                "message": n.message,
                "created_at": n.created_at,
                "reference_id": n.reference_id,
            }
            for n in events
        ]

        return Response(
            {
                "cadence": cadence,
                "digest_summary": f"{events.count()} security events in the last {cadence.lower()} window",
                "events": digest_lines,
            },
            status=status.HTTP_200_OK,
        )

    # ---------------------------------------------------------
    # Unread notifications
    # ---------------------------------------------------------

    @action(
        detail=False,
        methods=["get"],
        url_path="unread",
    )
    def unread(self, request):
        """
        Return unread notifications for the authenticated user.
        """

        queryset = self.get_queryset().filter(
            is_read=False
        )

        page = self.paginate_queryset(queryset)

        if page is not None:
            serializer = self.get_serializer(
                page,
                many=True,
            )
            return self.get_paginated_response(
                serializer.data
            )

        serializer = self.get_serializer(
            queryset,
            many=True,
        )

        return Response(serializer.data)

    # ---------------------------------------------------------
    # Unread count
    # ---------------------------------------------------------

    @action(
        detail=False,
        methods=["get"],
        url_path="unread-count",
    )
    def unread_count(self, request):
        """
        Return the number of unread notifications.
        """

        count = self.get_queryset().filter(
            is_read=False
        ).count()

        return Response(
            {
                "count": count,
            },
            status=status.HTTP_200_OK,
        )

    # ---------------------------------------------------------
    # Mark single notification as read
    # ---------------------------------------------------------

    @action(
        detail=True,
        methods=["post"],
        url_path="mark-read",
    )
    def mark_read(self, request, pk=None):
        notification = self.get_object()

        if notification.is_read:
            return Response(
                {
                    "message": "Notification is already marked as read.",
                    "is_read": True,
                },
                status=status.HTTP_200_OK,
            )

        notification.is_read = True

        notification.save(
            update_fields=["is_read"]
        )

        return Response(
            {
                "message": "Notification marked as read.",
                "is_read": True,
            },
            status=status.HTTP_200_OK,
        )

    # ---------------------------------------------------------
    # Mark single notification as unread
    # ---------------------------------------------------------

    @action(
        detail=True,
        methods=["post"],
        url_path="mark-unread",
    )
    def mark_unread(self, request, pk=None):
        notification = self.get_object()

        if not notification.is_read:
            return Response(
                {
                    "message": "Notification is already unread.",
                    "is_read": False,
                },
                status=status.HTTP_200_OK,
            )

        notification.is_read = False

        notification.save(
            update_fields=["is_read"]
        )

        return Response(
            {
                "message": "Notification marked as unread.",
                "is_read": False,
            },
            status=status.HTTP_200_OK,
        )

    # ---------------------------------------------------------
    # Mark all notifications as read
    # ---------------------------------------------------------

    @action(
        detail=False,
        methods=["post"],
        url_path="mark-all-read",
    )
    def mark_all_read(self, request):
        """
        Mark all unread notifications belonging to the
        authenticated user as read.
        """

        queryset = self.get_queryset().filter(
            is_read=False
        )

        updated_count = queryset.update(
            is_read=True
        )

        return Response(
            {
                "message": "All notifications marked as read.",
                "updated_count": updated_count,
            },
            status=status.HTTP_200_OK,
        )

    # ---------------------------------------------------------
    # Delete notification
    # ---------------------------------------------------------

    def destroy(self, request, *args, **kwargs):
        """
        Users can delete their own notifications.
        """

        notification = self.get_object()

        notification.delete()

        return Response(
            {
                "message": "Notification deleted."
            },
            status=status.HTTP_204_NO_CONTENT,
        )





class NotificationPreferenceView(RetrieveUpdateAPIView):
    serializer_class = NotificationPreferenceSerializer

    permission_classes = [
        IsAuthenticated
    ]

    def get_object(self):

        preferences, _ = (
            NotificationPreference.objects
            .get_or_create(
                user=self.request.user
            )
        )

        return preferences