# Generated by Django 6.0.2 on 2026-09-09 10:58

import core.migration_utils
import django.db.migrations.operations.special
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_state',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.RunPython(
            code=core.migration_utils.backfill_account_states,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
