# Generated by Django 6.0.2 on 2026-08-26 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('forms_engine', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('target_type', models.CharField(choices=[('USER', 'Specific User'), ('ROLE', 'System Role'), ('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('TEAM', 'Team'), ('POSITION', 'Position')], max_length=20)),
                ('target_role', models.CharField(blank=True, max_length=30)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_rule', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_late_submission', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_schedules', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reporting_schedules', to=settings.AUTH_USER_MODEL)),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_schedules', to='companies.branch')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_schedules', to='organizations.department')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_schedules', to='organizations.position')),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_schedules', to='organizations.team')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reporting_schedules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_schedules', to='forms_engine.formtemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_date', models.DateField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('MISSED', 'Missed'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_obligations', to='companies.company')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_obligation', to='forms_engine.formsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_obligations', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='reporting_schedules.reportingschedule')),
            ],
            options={
                'ordering': ['-due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportingschedule',
            index=models.Index(fields=['company', 'frequency', 'is_active'], name='reporting_s_company_9a9bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingobligation',
            index=models.Index(fields=['company', 'status', 'due_at'], name='reporting_s_company_13367e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingobligation',
            index=models.Index(fields=['user', 'status', 'due_at'], name='reporting_s_user_id_eb9dd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportingobligation',
            constraint=models.UniqueConstraint(fields=('schedule', 'user', 'reporting_date'), name='unique_schedule_user_reporting_date'),
        ),
    ]
