# Generated by Django 6.0.2 on 2026-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingobligation',
            name='final_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingobligation',
            name='morning_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
