# Generated by Django 6.0.2 on 2026-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowactionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
