# Generated by Django 6.0.2 on 2026-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowactionlog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflowstepinstance',
            name='routing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
