# Generated by Django 6.0.2 on 2026-08-27 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('organizations', '0003_employeeprofile_terminated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('RWF', 'Rwandan Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='RWF', max_length=10)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_compensations', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_records', to='organizations.employeeprofile')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['company', 'employee', 'is_current'], name='organizatio_company_42f3a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PositionCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('VIEW_ALL_EMPLOYEES', 'View All Employees'), ('MANAGE_EMPLOYEES', 'Manage Employees'), ('MANAGE_ORGANIZATION', 'Manage Organization'), ('VIEW_ALL_REPORTS', 'View All Reports'), ('APPROVE_REPORTS', 'Approve Reports'), ('RECEIVE_REPORTS', 'Receive Reports'), ('APPROVE_REQUESTS', 'Approve Requests'), ('REVIEW_SUBMISSIONS', 'Review Submissions'), ('MANAGE_PROJECTS', 'Manage Projects'), ('MANAGE_TASKS', 'Manage Tasks'), ('MANAGE_DOCUMENTS', 'Manage Documents'), ('VIEW_MANAGEMENT_DOCUMENTS', 'View Management Documents'), ('VIEW_COMPENSATION', 'View Compensation'), ('MANAGE_COMPENSATION', 'Manage Compensation'), ('VIEW_COMPENSATION_HISTORY', 'View Compensation History'), ('MANAGE_COMPENSATION_ACCESS', 'Manage Compensation Access'), ('VIEW_EXECUTIVE_DASHBOARD', 'View Executive Dashboard'), ('VIEW_COMPANY_ANALYTICS', 'View Company Analytics'), ('VIEW_FINANCIAL_REPORTS', 'View Financial Reports'), ('MANAGE_COMPANY_PLANS', 'Manage Company Plans'), ('PLATFORM_ADMIN', 'Platform Admin')], max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_capability_grants', to='companies.company')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_capabilities_granted', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='organizations.position')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'position', 'capability'), name='unique_company_position_capability')],
            },
        ),
        migrations.CreateModel(
            name='UserCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('VIEW_ALL_EMPLOYEES', 'View All Employees'), ('MANAGE_EMPLOYEES', 'Manage Employees'), ('MANAGE_ORGANIZATION', 'Manage Organization'), ('VIEW_ALL_REPORTS', 'View All Reports'), ('APPROVE_REPORTS', 'Approve Reports'), ('RECEIVE_REPORTS', 'Receive Reports'), ('APPROVE_REQUESTS', 'Approve Requests'), ('REVIEW_SUBMISSIONS', 'Review Submissions'), ('MANAGE_PROJECTS', 'Manage Projects'), ('MANAGE_TASKS', 'Manage Tasks'), ('MANAGE_DOCUMENTS', 'Manage Documents'), ('VIEW_MANAGEMENT_DOCUMENTS', 'View Management Documents'), ('VIEW_COMPENSATION', 'View Compensation'), ('MANAGE_COMPENSATION', 'Manage Compensation'), ('VIEW_COMPENSATION_HISTORY', 'View Compensation History'), ('MANAGE_COMPENSATION_ACCESS', 'Manage Compensation Access'), ('VIEW_EXECUTIVE_DASHBOARD', 'View Executive Dashboard'), ('VIEW_COMPANY_ANALYTICS', 'View Company Analytics'), ('VIEW_FINANCIAL_REPORTS', 'View Financial Reports'), ('MANAGE_COMPANY_PLANS', 'Manage Company Plans'), ('PLATFORM_ADMIN', 'Platform Admin')], max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capability_grants', to='companies.company')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities_granted', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'user', 'is_active'], name='organizatio_company_2260b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'user', 'capability'), name='unique_company_user_capability')],
            },
        ),
    ]
