# Generated by Django 6.0.2 on 2026-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_positioncapabilitygrant_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncapabilitygrant',
            name='capability',
            field=models.CharField(choices=[('VIEW_ALL_EMPLOYEES', 'View All Employees'), ('MANAGE_EMPLOYEES', 'Manage Employees'), ('MANAGE_ORGANIZATION', 'Manage Organization'), ('VIEW_ALL_REPORTS', 'View All Reports'), ('APPROVE_REPORTS', 'Approve Reports'), ('RECEIVE_REPORTS', 'Receive Reports'), ('APPROVE_REQUESTS', 'Approve Requests'), ('REVIEW_SUBMISSIONS', 'Review Submissions'), ('MANAGE_PROJECTS', 'Manage Projects'), ('MANAGE_TASKS', 'Manage Tasks'), ('MANAGE_DOCUMENTS', 'Manage Documents'), ('VIEW_MANAGEMENT_DOCUMENTS', 'View Management Documents'), ('VIEW_OFFICIAL_RECORDS', 'View Official Records'), ('ISSUE_OFFICIAL_RECORDS', 'Issue Official Records'), ('EXPORT_OFFICIAL_RECORDS', 'Export Official Records'), ('VOID_OFFICIAL_RECORDS', 'Void Official Records'), ('EXPORT_COMPENSATION', 'Export Compensation'), ('GLOBAL_SEARCH', 'Global Search'), ('IMPORT_EMPLOYEES', 'Import Employees'), ('IMPORT_OPERATIONAL_DATA', 'Import Operational Data'), ('EXPORT_OPERATIONAL_DATA', 'Export Operational Data'), ('BULK_MANAGE_EMPLOYEES', 'Bulk Manage Employees'), ('BULK_MANAGE_TASKS', 'Bulk Manage Tasks'), ('BULK_MANAGE_RECORDS', 'Bulk Manage Records'), ('VIEW_COMPENSATION', 'View Compensation'), ('MANAGE_COMPENSATION', 'Manage Compensation'), ('VIEW_COMPENSATION_HISTORY', 'View Compensation History'), ('MANAGE_COMPENSATION_ACCESS', 'Manage Compensation Access'), ('VIEW_EXECUTIVE_DASHBOARD', 'View Executive Dashboard'), ('VIEW_COMPANY_ANALYTICS', 'View Company Analytics'), ('VIEW_FINANCIAL_REPORTS', 'View Financial Reports'), ('MANAGE_COMPANY_PLANS', 'Manage Company Plans'), ('PLATFORM_ADMIN', 'Platform Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usercapabilitygrant',
            name='capability',
            field=models.CharField(choices=[('VIEW_ALL_EMPLOYEES', 'View All Employees'), ('MANAGE_EMPLOYEES', 'Manage Employees'), ('MANAGE_ORGANIZATION', 'Manage Organization'), ('VIEW_ALL_REPORTS', 'View All Reports'), ('APPROVE_REPORTS', 'Approve Reports'), ('RECEIVE_REPORTS', 'Receive Reports'), ('APPROVE_REQUESTS', 'Approve Requests'), ('REVIEW_SUBMISSIONS', 'Review Submissions'), ('MANAGE_PROJECTS', 'Manage Projects'), ('MANAGE_TASKS', 'Manage Tasks'), ('MANAGE_DOCUMENTS', 'Manage Documents'), ('VIEW_MANAGEMENT_DOCUMENTS', 'View Management Documents'), ('VIEW_OFFICIAL_RECORDS', 'View Official Records'), ('ISSUE_OFFICIAL_RECORDS', 'Issue Official Records'), ('EXPORT_OFFICIAL_RECORDS', 'Export Official Records'), ('VOID_OFFICIAL_RECORDS', 'Void Official Records'), ('EXPORT_COMPENSATION', 'Export Compensation'), ('GLOBAL_SEARCH', 'Global Search'), ('IMPORT_EMPLOYEES', 'Import Employees'), ('IMPORT_OPERATIONAL_DATA', 'Import Operational Data'), ('EXPORT_OPERATIONAL_DATA', 'Export Operational Data'), ('BULK_MANAGE_EMPLOYEES', 'Bulk Manage Employees'), ('BULK_MANAGE_TASKS', 'Bulk Manage Tasks'), ('BULK_MANAGE_RECORDS', 'Bulk Manage Records'), ('VIEW_COMPENSATION', 'View Compensation'), ('MANAGE_COMPENSATION', 'Manage Compensation'), ('VIEW_COMPENSATION_HISTORY', 'View Compensation History'), ('MANAGE_COMPENSATION_ACCESS', 'Manage Compensation Access'), ('VIEW_EXECUTIVE_DASHBOARD', 'View Executive Dashboard'), ('VIEW_COMPANY_ANALYTICS', 'View Company Analytics'), ('VIEW_FINANCIAL_REPORTS', 'View Financial Reports'), ('MANAGE_COMPANY_PLANS', 'Manage Company Plans'), ('PLATFORM_ADMIN', 'Platform Admin')], max_length=100),
        ),
    ]
