# Generated by Django 6.0.2 on 2026-09-20 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinvite_unique_pending_invite_email_per_company_ci'),
        ('organizations', '0010_alter_positioncapabilitygrant_capability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_positions', to='organizations.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.team'),
        ),
    ]
