# Generated by Django 6.0.2 on 2026-08-27 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('organizations', '0004_employeecompensation_positioncapabilitygrant_and_more'),
        ('projects', '0002_initial'),
        ('tasks', '0002_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=120)),
                ('request_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('EQUIPMENT', 'Equipment'), ('MAINTENANCE', 'Maintenance'), ('BUDGET', 'Budget'), ('STOCK', 'Stock'), ('VEHICLE', 'Vehicle'), ('LEAVE', 'Leave'), ('TRAVEL', 'Travel'), ('HR', 'Human Resources'), ('OPERATIONAL', 'Operational'), ('CUSTOM', 'Custom')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='RWF', max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to='companies.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='organizations.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='projects.project')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='tasks.task')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'priority'], name='requests_ap_company_a4ea31_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'request_number'), name='unique_company_request_number')],
            },
        ),
    ]
