# Generated by Django 6.0.2 on 2026-09-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_setup', '0007_officialrecordpolicy_notificationpolicy'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='request_type_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='company_setup.requesttypedefinition'),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='request_type_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
