# Generated by Django 6.0.2 on 2026-09-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0003_remove_formtemplate_unique_company_form_template_code_and_more'),
        ('requests_app', '0002_businessrequest_request_type_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='form_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_request', to='forms_engine.formsubmission'),
        ),
    ]
