# Generated by Django 6.0.2 on 2026-09-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_businessrequest_form_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
