# Generated by Django 6.0.2 on 2026-08-26 10:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('organizations', '0002_initial'),
        ('projects', '0002_initial'),
        ('tasks', '0002_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DAILY_REPORT', 'Daily Report'), ('WEEKLY_REPORT', 'Weekly Report'), ('MONTHLY_REPORT', 'Monthly Report'), ('PRODUCTION', 'Production'), ('DELIVERY', 'Delivery'), ('COLLECTION', 'Collection'), ('INSPECTION', 'Inspection'), ('MAINTENANCE', 'Maintenance'), ('FIELD_ACTIVITY', 'Field Activity'), ('SALES', 'Sales'), ('INCIDENT', 'Incident'), ('REQUEST', 'Request'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_drafts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='organizations.department')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='organizations.team')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('reporting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('schema_snapshot', models.JSONField(blank=True, default=dict)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='companies.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='organizations.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='tasks.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='organizations.team')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms_engine.formtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long Text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Date & Time'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('LOCATION', 'Location')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.formtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['company', 'category', 'is_active'], name='forms_engin_company_4d4dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_form_template_code'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['company', 'status', 'reporting_date'], name='forms_engin_company_fb61ce_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['company', 'branch', 'reporting_date'], name='forms_engin_company_85055a_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['template', 'reporting_date'], name='forms_engin_templat_009f02_idx'),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(fields=('company', 'reference_number'), name='unique_company_form_submission_reference'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='unique_form_field_key'),
        ),
    ]
