# Generated by Django 6.0.2 on 2026-09-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinvite_unique_pending_invite_email_per_company_ci'),
        ('forms_engine', '0002_formtemplate_lifecycle_status'),
        ('organizations', '0009_alter_positioncapabilitygrant_capability_and_more'),
        ('workflows', '0003_workflowinstance_workflow_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formtemplate',
            name='unique_company_form_template_code',
        ),
        migrations.AddField(
            model_name='formfield',
            name='classification',
            field=models.CharField(default='NORMAL', max_length=40),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='audience_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='forms_engine.formtemplate'),
        ),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code', 'version'), name='unique_company_form_template_version'),
        ),
    ]
