# Generated by Django 6.0.2 on 2026-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0003_remove_formtemplate_unique_company_form_template_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DAILY_REPORT', 'Daily Report'), ('WEEKLY_REPORT', 'Weekly Report'), ('MONTHLY_REPORT', 'Monthly Report'), ('PRODUCTION', 'Production'), ('DELIVERY', 'Delivery'), ('COLLECTION', 'Collection'), ('INSPECTION', 'Inspection'), ('MAINTENANCE', 'Maintenance'), ('FIELD_ACTIVITY', 'Field Activity'), ('SALES', 'Sales'), ('INCIDENT', 'Incident'), ('REQUEST', 'Request'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('field_schema', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
