# Generated by Django 6.0.2 on 2026-09-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0005_seed_form_starters'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='audience_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
