"""Stable public enum names, including labels used by schema hashing."""
ENUM_NAME_OVERRIDES = {'AIInsightSeverityEnum': [('INFO', 'Info'),
                           ('LOW', 'Low'),
                           ('MEDIUM', 'Medium'),
                           ('HIGH', 'High'),
                           ('CRITICAL', 'Critical')],
 'AIInsightStatusEnum': [('ACTIVE', 'Active'),
                         ('RESOLVED', 'Resolved'),
                         ('DISMISSED', 'Dismissed')],
 'ActivityActionEnum': [('TASK_CREATED', 'Task Created'),
                        ('TASK_UPDATED', 'Task Updated'),
                        ('TASK_DELETED', 'Task Deleted'),
                        ('TASK_ASSIGNED', 'Task Assigned'),
                        ('STATUS_CHANGED', 'Status Changed'),
                        ('PROJECT_CREATED', 'Project Created'),
                        ('PROJECT_UPDATED', 'Project Updated'),
                        ('PROJECT_DELETED', 'Project Deleted'),
                        ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'),
                        ('MEMBERSHIP_CREATED', 'Membership Created'),
                        ('MEMBERSHIP_UPDATED', 'Membership Updated'),
                        ('ROLE_CHANGED', 'Role Changed'),
                        ('REPORT_SUBMITTED', 'Report Submitted'),
                        ('REPORT_UPDATED', 'Report Updated'),
                        ('REPORT_DELETED', 'Report Deleted'),
                        ('COMMENT_ADDED', 'Comment Added'),
                        ('COMMENT_UPDATED', 'Comment Updated'),
                        ('COMMENT_DELETED', 'Comment Deleted'),
                        ('EMPLOYEE_CREATED', 'Employee Created'),
                        ('EMPLOYEE_UPDATED', 'Employee Updated'),
                        ('EMPLOYEE_SUSPENDED', 'Employee Suspended'),
                        ('EMPLOYEE_ACTIVATED', 'Employee Activated'),
                        ('EMPLOYEE_TERMINATED', 'Employee Terminated'),
                        ('EMPLOYEE_TRANSFERRED', 'Employee Transferred'),
                        ('DEPARTMENT_CREATED', 'Department Created'),
                        ('DEPARTMENT_UPDATED', 'Department Updated'),
                        ('DEPARTMENT_DELETED', 'Department Deleted'),
                        ('TEAM_CREATED', 'Team Created'),
                        ('TEAM_UPDATED', 'Team Updated'),
                        ('TEAM_DELETED', 'Team Deleted'),
                        ('POSITION_CREATED', 'Position Created'),
                        ('POSITION_UPDATED', 'Position Updated'),
                        ('POSITION_DELETED', 'Position Deleted'),
                        ('LOGIN', 'Login'),
                        ('LOGOUT', 'Logout'),
                        ('SECURITY_EVENT', 'Security Event'),
                        ('SYSTEM_EVENT', 'System Event'),
                        ('AI_INSIGHT_CREATED', 'AI Insight Created')],
 'AuditSeverityEnum': [('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')],
 'AuditStatusEnum': [('SUCCESS', 'Success'), ('FAILED', 'Failed')],
 'BusinessRequestStatusEnum': [('DRAFT', 'Draft'),
                               ('SUBMITTED', 'Submitted'),
                               ('UNDER_REVIEW', 'Under Review'),
                               ('RETURNED', 'Returned'),
                               ('APPROVED', 'Approved'),
                               ('REJECTED', 'Rejected'),
                               ('CANCELLED', 'Cancelled'),
                               ('FULFILLED', 'Fulfilled'),
                               ('CLOSED', 'Closed')],
 'CompanyPlanStatusEnum': [('DRAFT', 'Draft'),
                           ('ACTIVE', 'Active'),
                           ('COMPLETED', 'Completed'),
                           ('CANCELLED', 'Cancelled'),
                           ('ARCHIVED', 'Archived')],
 'DocumentStatusEnum': [('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')],
 'EmployeeDelegationStatusEnum': [('SCHEDULED', 'Scheduled'),
                                  ('ACTIVE', 'Active'),
                                  ('EXPIRED', 'Expired'),
                                  ('CANCELLED', 'Cancelled')],
 'EmployeeProfileStatusEnum': [('ACTIVE', 'Active'),
                               ('ON_LEAVE', 'On Leave'),
                               ('SUSPENDED', 'Suspended'),
                               ('TERMINATED', 'Terminated')],
 'FieldActivityStatusEnum': [('PLANNED', 'Planned'),
                             ('IN_PROGRESS', 'In Progress'),
                             ('COMPLETED', 'Completed'),
                             ('CANCELLED', 'Cancelled')],
 'FieldStopStatusEnum': [('PENDING', 'Pending'),
                         ('ARRIVED', 'Arrived'),
                         ('COMPLETED', 'Completed'),
                         ('SKIPPED', 'Skipped')],
 'FormSubmissionStatusEnum': [('DRAFT', 'Draft'),
                              ('SUBMITTED', 'Submitted'),
                              ('UNDER_REVIEW', 'Under Review'),
                              ('RETURNED', 'Returned'),
                              ('APPROVED', 'Approved'),
                              ('REJECTED', 'Rejected'),
                              ('CANCELLED', 'Cancelled'),
                              ('CLOSED', 'Closed')],
 'FormTemplateCategoryEnum': [('DAILY_REPORT', 'Daily Report'),
                              ('WEEKLY_REPORT', 'Weekly Report'),
                              ('MONTHLY_REPORT', 'Monthly Report'),
                              ('PRODUCTION', 'Production'),
                              ('DELIVERY', 'Delivery'),
                              ('COLLECTION', 'Collection'),
                              ('INSPECTION', 'Inspection'),
                              ('MAINTENANCE', 'Maintenance'),
                              ('FIELD_ACTIVITY', 'Field Activity'),
                              ('SALES', 'Sales'),
                              ('INCIDENT', 'Incident'),
                              ('REQUEST', 'Request'),
                              ('CUSTOM', 'Custom')],
 'ImportJobStatusStatusEnum': [('UPLOADED', 'Uploaded'),
                               ('VALIDATING', 'Validating'),
                               ('READY', 'Ready'),
                               ('COMPLETED', 'Completed'),
                               ('FAILED', 'Failed'),
                               ('CANCELLED', 'Cancelled')],
 'InvitationStatusEnum': [('PENDING', 'Pending'),
                          ('ACCEPTED', 'Accepted'),
                          ('EXPIRED', 'Expired'),
                          ('REVOKED', 'Revoked')],
 'LifecycleStatusEnum': [('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')],
 'OfficialRecordStatusEnum': [('ACTIVE', 'Active'),
                              ('SUPERSEDED', 'Superseded'),
                              ('VOID', 'Void'),
                              ('ARCHIVED', 'Archived')],
 'PlanItemStatusEnum': [('PENDING', 'Pending'),
                        ('IN_PROGRESS', 'In Progress'),
                        ('COMPLETED', 'Completed'),
                        ('BLOCKED', 'Blocked'),
                        ('CANCELLED', 'Cancelled')],
 'PlatformEmailDeliveryStatusEnum': [('PENDING', 'Pending'),
                                     ('SENT', 'Sent'),
                                     ('FAILED', 'Failed')],
 'PriorityEnum': [('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')],
 'ProjectMembershipRoleEnum': [('OWNER', 'Owner'),
                               ('MANAGER', 'Manager'),
                               ('CONTRIBUTOR', 'Contributor'),
                               ('VIEWER', 'Viewer')],
 'ReportingObligationStatusEnum': [('PENDING', 'Pending'),
                                   ('DRAFT', 'Draft'),
                                   ('SUBMITTED', 'Submitted'),
                                   ('LATE', 'Late'),
                                   ('MISSED', 'Missed'),
                                   ('APPROVED', 'Approved'),
                                   ('RETURNED', 'Returned'),
                                   ('REJECTED', 'Rejected'),
                                   ('CANCELLED', 'Cancelled')],
 'SupportCategoryEnum': [('ACCOUNT', 'Account'),
                         ('SECURITY', 'Security'),
                         ('SUBSCRIPTION', 'Subscription'),
                         ('BILLING', 'Billing'),
                         ('REPORTING', 'Reporting'),
                         ('WORKFLOW', 'Workflow'),
                         ('EMPLOYEES', 'Employees'),
                         ('DOCUMENTS', 'Documents'),
                         ('FIELD_OPERATIONS', 'Field Operations'),
                         ('TECHNICAL', 'Technical'),
                         ('FEATURE_REQUEST', 'Feature Request'),
                         ('OTHER', 'Other')],
 'SupportStatusEnum': [('OPEN', 'Open'),
                       ('IN_PROGRESS', 'In progress'),
                       ('WAITING_FOR_CUSTOMER', 'Waiting for customer'),
                       ('RESOLVED', 'Resolved'),
                       ('CLOSED', 'Closed')],
 'TaskStatusEnum': [('pending', 'Pending'),
                    ('in_progress', 'In Progress'),
                    ('blocked', 'Blocked'),
                    ('done', 'Done')],
 'UserRoleEnum': [('SUPERUSER', 'Superuser'),
                  ('ADMIN', 'Admin'),
                  ('MANAGER', 'Manager'),
                  ('EMPLOYEE', 'Employee'),
                  ('INDIVIDUAL', 'Individual')],
 'WorkflowActionLogActionEnum': [('SUBMITTED', 'Submitted'),
                                 ('APPROVED', 'Approved'),
                                 ('REJECTED', 'Rejected'),
                                 ('RETURNED', 'Returned'),
                                 ('FORWARDED', 'Forwarded'),
                                 ('CANCELLED', 'Cancelled')],
 'WorkflowInstanceStatusEnum': [('IN_PROGRESS', 'In Progress'),
                                ('APPROVED', 'Approved'),
                                ('REJECTED', 'Rejected'),
                                ('RETURNED', 'Returned'),
                                ('CANCELLED', 'Cancelled')],
 'WorkflowStepInstanceStatusEnum': [('WAITING', 'Waiting'),
                                    ('PENDING', 'Pending'),
                                    ('APPROVED', 'Approved'),
                                    ('REJECTED', 'Rejected'),
                                    ('RETURNED', 'Returned'),
                                    ('SKIPPED', 'Skipped')],
 'WorkflowStepRecipientStatusEnum': [('PENDING', 'Pending'),
                                     ('APPROVED', 'Approved'),
                                     ('REJECTED', 'Rejected'),
                                     ('RETURNED', 'Returned'),
                                     ('SKIPPED', 'Skipped')]}

ENUM_NAME_OVERRIDES["PositionAssignmentScopeEnum"] = [("COMPANY", "Company-wide"), ("BRANCHES", "Selected locations")]
