# Generated by Django 6.0.2 on 2026-09-09 10:58

import core.migration_utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinvite_unique_pending_invite_email_per_company_ci'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=core.migration_utils.convert_support_message_ids,
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='visibility',
            field=models.CharField(choices=[('CUSTOMER', 'Customer visible'), ('INTERNAL', 'Internal support note')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='requested_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sensitivity',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RESTRICTED', 'Restricted'), ('SECURITY', 'Security'), ('BILLING', 'Billing')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supportmessage',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='reference',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_CUSTOMER', 'Waiting for customer'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=24),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['sensitivity', 'status'], name='support_sup_sensiti_e18b0a_idx'),
        ),
    ]
