# Generated by Django 6.0.2 on 2026-03-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_branch_manager'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('COMPANY', 'Company'), ('PROJECT', 'Project'), ('USER', 'User')], max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch'), ('project', 'Project')], max_length=20)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('collaboration_score', models.FloatField(default=0.0)),
                ('workload_balance_score', models.FloatField(default=0.0)),
                ('ai_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
