# Generated by Django 6.0.2 on 2026-08-13 19:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalyticsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch'), ('PROJECT', 'Project'), ('USER', 'User')], max_length=20)),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('COMPANY_SUMMARY', 'Company Summary'), ('PROJECT_SUMMARY', 'Project Summary'), ('BRANCH_SUMMARY', 'Branch Summary'), ('USER_SUMMARY', 'User Summary'), ('WORKLOAD_ALERT', 'Workload Alert'), ('RISK_ALERT', 'Risk Alert'), ('PERFORMANCE_ALERT', 'Performance Alert')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch'), ('project', 'Project')], max_length=20)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('in_progress_tasks', models.PositiveIntegerField(default=0)),
                ('blocked_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('active_projects', models.PositiveIntegerField(default=0)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('overdue_rate', models.FloatField(default=0.0)),
                ('collaboration_score', models.FloatField(default=0.0)),
                ('workload_balance_score', models.FloatField(default=0.0)),
                ('ai_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
