# Generated by Django 6.0.2 on 2026-03-08 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_ai', '0001_initial'),
        ('companies', '0003_rename_company_branch_company_and_more'),
        ('projects', '0002_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('COMPANY_SUMMARY', 'Company Summary'), ('PROJECT_SUMMARY', 'Project Summary'), ('WORKLOAD_ALERT', 'Workload Alert'), ('RISK_ALERT', 'Risk Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='projects.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
