# Generated by Django 6.0.2 on 2026-08-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_ai', '0003_initial'),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalyticsrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='projects.project'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='companies.company'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='aianalyticsrecord',
            index=models.Index(fields=['company', '-generated_at'], name='analytics_rec_company_date'),
        ),
        migrations.AddIndex(
            model_name='aianalyticsrecord',
            index=models.Index(fields=['level', '-generated_at'], name='analytics_rec_level_date'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['company', '-generated_at'], name='ai_insight_company_date'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['company', 'status'], name='ai_insight_company_status'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['project', '-generated_at'], name='ai_insight_project_date'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['branch', '-generated_at'], name='ai_insight_branch_date'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['company', 'snapshot_type', '-generated_at'], name='analytics_snap_company_type'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['project', '-generated_at'], name='analytics_snap_project_date'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['branch', '-generated_at'], name='analytics_snap_branch_date'),
        ),
    ]
