# Generated by Django 6.0.2 on 2026-08-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('reports', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportfield',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.report'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['company', '-created_at'], name='reports_rep_company_c5a865_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by'], name='reports_rep_created_61f2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project'], name='reports_rep_project_0acf13_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['task'], name='reports_rep_task_id_7c0982_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['branch'], name='reports_rep_branch__ce56ba_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['visibility'], name='reports_rep_visibil_4b4ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['report', 'created_at'], name='reports_rep_report__32ad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['author'], name='reports_rep_author__b7f270_idx'),
        ),
    ]
