# Generated by Django 6.0.2 on 2026-09-09 10:58

import core.migration_utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinvite_unique_pending_invite_email_per_company_ci'),
        ('security', '0003_alter_auditlog_object_id'),
        ('support', '0002_supportmessage_edited_at_supportmessage_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=core.migration_utils.convert_security_ids,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='activesession',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='auditlog',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='loginhistory',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='otp',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='trusteddevice',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SupportAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('ENDED', 'Ended')], db_index=True, default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='security_au_company_96a7b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='failedloginattempt',
            name='security_fa_email_fbe5c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='security_ot_user_id_e6855d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='failedloginattempt',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activesession',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activesession',
            name='termination_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activesession',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('LOGOUT', 'Logout'), ('ADMIN', 'Administrator'), ('PASSWORD_RESET', 'Password reset'), ('ACCOUNT_STATE', 'Account state'), ('SECURITY', 'Security'), ('EXPIRED', 'Expired')], max_length=30),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='failedloginattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedloginattempt',
            name='email_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedloginattempt',
            name='email_hint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='challenge_id',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='code_digest',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='device_token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='otp',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login')], default='LOGIN', max_length=20),
        ),
        migrations.AddField(
            model_name='otp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='token_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user_agent_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            code=core.migration_utils.backfill_security,
        ),
        migrations.AlterField(
            model_name='otp',
            name='challenge_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='browser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('API', 'API'), ('PLATFORM', 'Platform'), ('SUPPORT', 'Support')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['company', 'is_active'], name='security_ac_company_538b41_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='security_au_company_e45335_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'action', 'severity'], name='security_au_company_89a3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='security_au_user_id_c0deef_idx'),
        ),
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['email_hash', 'ip_address'], name='security_fa_email_h_ce74ed_idx'),
        ),
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['locked_until'], name='security_fa_locked__0406ea_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['company', 'created_at'], name='security_lo_company_186bce_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['successful', 'created_at'], name='security_lo_success_7b3b58_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='security_ot_user_id_b3aa22_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['challenge_id'], name='security_ot_challen_6882ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='failedloginattempt',
            constraint=models.UniqueConstraint(fields=('email_hash', 'ip_address'), name='unique_failed_login_principal_ip'),
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.UniqueConstraint(fields=('user', 'token_hash'), name='unique_user_trusted_device_token'),
        ),
        migrations.AddField(
            model_name='supportaccesssession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_support_access_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportaccesssession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_sessions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='supportaccesssession',
            name='support_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportaccesssession',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_sessions', to='support.supportticket'),
        ),
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='failedloginattempt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='fingerprint',
        ),
        migrations.AddIndex(
            model_name='supportaccesssession',
            index=models.Index(fields=['support_agent', 'status', 'expires_at'], name='security_su_support_540749_idx'),
        ),
        migrations.AddIndex(
            model_name='supportaccesssession',
            index=models.Index(fields=['company', 'status'], name='security_su_company_10fafd_idx'),
        ),
    ]
