# Generated by Django 6.0.2 on 2026-08-28 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('forms_engine', '0001_initial'),
        ('organizations', '0004_employeecompensation_positioncapabilitygrant_and_more'),
        ('projects', '0002_initial'),
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('COLLECTION', 'Collection'), ('INSPECTION', 'Inspection'), ('MAINTENANCE', 'Maintenance'), ('SALES_VISIT', 'Sales Visit'), ('SERVICE_VISIT', 'Service Visit'), ('SITE_VISIT', 'Site Visit'), ('ROUTE', 'Route'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('vehicle_reference', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('started_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_activities', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_activities', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='organizations.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_activities', to='tasks.task')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('stop_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('COLLECTION', 'Collection'), ('INSPECTION', 'Inspection'), ('SERVICE', 'Service'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SITE', 'Site'), ('OTHER', 'Other')], max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='field_operations.fieldactivity')),
                ('form_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_stop', to='forms_engine.formsubmission')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldStopMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('text_value', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='field_operations.fieldstop')),
            ],
        ),
        migrations.AddIndex(
            model_name='fieldactivity',
            index=models.Index(fields=['company', 'activity_date', 'status'], name='field_opera_company_f18bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldactivity',
            index=models.Index(fields=['employee', 'activity_date'], name='field_opera_employe_9e375c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldstop',
            constraint=models.UniqueConstraint(fields=('activity', 'sequence'), name='unique_field_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='fieldstopmetric',
            constraint=models.UniqueConstraint(fields=('stop', 'key'), name='unique_field_stop_metric'),
        ),
    ]
