# Generated by Django 6.0.2 on 2026-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_ASSIGNED', 'Task Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('MEMBERSHIP_CREATED', 'Membership Created'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('ROLE_CHANGED', 'Role Changed'), ('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_UPDATED', 'Report Updated'), ('REPORT_DELETED', 'Report Deleted'), ('COMMENT_ADDED', 'Comment Added'), ('COMMENT_UPDATED', 'Comment Updated'), ('COMMENT_DELETED', 'Comment Deleted'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_SUSPENDED', 'Employee Suspended'), ('EMPLOYEE_ACTIVATED', 'Employee Activated'), ('EMPLOYEE_TERMINATED', 'Employee Terminated'), ('EMPLOYEE_TRANSFERRED', 'Employee Transferred'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DEPARTMENT_DELETED', 'Department Deleted'), ('TEAM_CREATED', 'Team Created'), ('TEAM_UPDATED', 'Team Updated'), ('TEAM_DELETED', 'Team Deleted'), ('POSITION_CREATED', 'Position Created'), ('POSITION_UPDATED', 'Position Updated'), ('POSITION_DELETED', 'Position Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SECURITY_EVENT', 'Security Event'), ('SYSTEM_EVENT', 'System Event'), ('AI_INSIGHT_CREATED', 'AI Insight Created')], max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
