# Generated by Django 6.0.2 on 2026-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_branch_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companyinvite',
            old_name='Company',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'name')},
        ),
    ]
