# Generated by Django 6.0.2 on 2026-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_from_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
