# Generated by Django 6.0.2 on 2026-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='official_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
