# Generated by Django 6.0.2 on 2026-09-09 10:58

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_delete_legacy_company_setup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyinvite',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('company'), condition=models.Q(('status', 'PENDING')), name='unique_pending_invite_email_per_company_ci'),
        ),
    ]
