# Generated by Django 6.0.2 on 2026-09-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinvite_unique_pending_invite_email_per_company_ci'),
        ('organizations', '0011_position_branch_position_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvite',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='organizations.position'),
        ),
    ]
