# Generated by Django 6.0.2 on 2026-08-28 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_official_name_company_registration_number'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('REPORT', 'Report'), ('REQUEST', 'Request'), ('FORM_SUBMISSION', 'Form Submission'), ('PLAN', 'Plan'), ('FIELD_SUMMARY', 'Field Summary'), ('OTHER', 'Other')], max_length=30)),
                ('record_number', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=64)),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('approval_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('VOID', 'Void'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_records', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_records', to='companies.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_official_records', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_records', to='records_management.officialrecord')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('PRINT', 'Print'), ('CSV', 'CSV'), ('XLSX', 'Excel')], max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_exports', to='companies.company')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_exports', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='records_management.officialrecord')),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_sequences', to='companies.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='officialrecord',
            index=models.Index(fields=['company', 'record_type', 'status'], name='records_man_company_4e704c_idx'),
        ),
        migrations.AddIndex(
            model_name='officialrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='records_man_content_5d4e2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialrecord',
            constraint=models.UniqueConstraint(fields=('company', 'record_number'), name='unique_official_record_number'),
        ),
        migrations.AddConstraint(
            model_name='recordsequence',
            constraint=models.UniqueConstraint(fields=('company', 'prefix', 'year'), name='unique_record_sequence'),
        ),
    ]
