# Generated by Django 6.0.2 on 2026-08-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officialrecord',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officialrecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialrecord',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_official_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
