from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("company_setup", "0003_rolepreset"), ("forms_engine", "0002_formtemplate_lifecycle_status"), ("workflows", "0001_initial")]
    operations = [
        migrations.CreateModel(name="FieldActivityTemplate", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("activity_type", models.CharField(max_length=30)), ("require_arrival", models.BooleanField(default=True)), ("require_completion", models.BooleanField(default=True)), ("require_location", models.BooleanField(default=False)), ("require_photo", models.BooleanField(default=False)), ("require_signature", models.BooleanField(default=False)), ("require_notes", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="field_activity_templates", to="companies.company")), ("form_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="field_activity_templates", to="forms_engine.formtemplate"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="RequestTypeDefinition", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.SlugField(max_length=100)), ("name", models.CharField(max_length=120)), ("description", models.TextField(blank=True)), ("icon", models.CharField(blank=True, max_length=50)), ("sensitive", models.BooleanField(default=False)), ("amount_enabled", models.BooleanField(default=False)), ("amount_required", models.BooleanField(default=False)), ("quantity_enabled", models.BooleanField(default=False)), ("quantity_required", models.BooleanField(default=False)), ("needed_by_enabled", models.BooleanField(default=True)), ("needed_by_required", models.BooleanField(default=False)), ("attachments_allowed", models.BooleanField(default=True)), ("attachments_required", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="request_type_definitions", to="companies.company")), ("form_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="request_type_definitions", to="forms_engine.formtemplate")), ("workflow", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="request_type_definitions", to="workflows.workflowdefinition"))], options={"ordering": ["name"]}),
        migrations.AddConstraint(model_name="fieldactivitytemplate", constraint=models.UniqueConstraint(fields=("company", "name"), name="unique_company_field_template_name")),
        migrations.AddConstraint(model_name="requesttypedefinition", constraint=models.UniqueConstraint(fields=("company", "code"), name="unique_company_request_type_code")),
    ]