# Generated by Django 6.0.2 on 2026-09-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_setup', '0007_officialrecordpolicy_notificationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetupstate',
            name='setup_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
