# Generated by Django 6.0.2 on 2026-08-13 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_INVITE', 'Project Invitation'), ('OWNERSHIP_TRANSFERRED', 'Project Ownership Transferred'), ('MEMBERSHIP_CREATED', 'Project Membership Created'), ('MEMBERSHIP_UPDATED', 'Project Membership Updated'), ('ROLE_CHANGED', 'Project Role Changed'), ('REPORT_CREATED', 'Report Created'), ('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_COMMENT', 'Report Comment'), ('COMMENT_ADDED', 'Comment Added'), ('COMMENT_REPLY', 'Comment Reply'), ('INVITATION', 'Company Invitation'), ('SECURITY', 'Security Event'), ('SYSTEM', 'System Notification'), ('AI_INSIGHT', 'AI Insight')], default='SYSTEM', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
