# Generated by Django 6.0.2 on 2026-08-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_email_footer_company_email_from_name_and_more'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('task_assignments', models.BooleanField(default=True)),
                ('task_updates', models.BooleanField(default=False)),
                ('project_updates', models.BooleanField(default=True)),
                ('reports', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=False)),
                ('organization_updates', models.BooleanField(default=True)),
                ('subscription_updates', models.BooleanField(default=True)),
                ('ai_insights', models.BooleanField(default=False)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_cadence', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('NONE', 'None')], default='DAILY', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='notificatio_company_25050e_idx'), models.Index(fields=['recipient_email', 'created_at'], name='notificatio_recipie_5d8efd_idx')],
            },
        ),
    ]
