# Generated by Django 6.0.2 on 2026-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_INVITE', 'Project Invitation'), ('OWNERSHIP_TRANSFERRED', 'Project Ownership Transferred'), ('MEMBERSHIP_CREATED', 'Project Membership Created'), ('MEMBERSHIP_UPDATED', 'Project Membership Updated'), ('ROLE_CHANGED', 'Project Role Changed'), ('REPORT_CREATED', 'Report Created'), ('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_COMMENT', 'Report Comment'), ('COMMENT_ADDED', 'Comment Added'), ('COMMENT_REPLY', 'Comment Reply'), ('INVITATION', 'Company Invitation'), ('SECURITY', 'Security Event'), ('NEW_LOGIN', 'New Login Detected'), ('OTP_SUCCESS', 'OTP Verified'), ('OTP_FAILED', 'OTP Failed'), ('OTP_EXPIRED', 'OTP Expired'), ('OTP_DELIVERY', 'OTP Delivery'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_INTERVENTION', 'Account Intervention'), ('SECURITY_DIGEST', 'Security Digest'), ('SYSTEM', 'System Notification'), ('AI_INSIGHT', 'AI Insight'), ('WORKFLOW_ACTION', 'Workflow Action'), ('REQUEST_UPDATE', 'Request Update'), ('REPORT_DUE', 'Report Due'), ('REPORT_OVERDUE', 'Report Overdue')], default='SYSTEM', max_length=40),
        ),
    ]
