from rest_framework.throttling import UserRateThrottle, AnonRateThrottle
class LoginRateThrottle(AnonRateThrottle): scope='login'
class VerificationRateThrottle(AnonRateThrottle): scope='verification'
class PasswordResetRateThrottle(AnonRateThrottle): scope='password_reset'
class InviteRateThrottle(UserRateThrottle): scope='invite'
class ExportRateThrottle(UserRateThrottle): scope='export'
class ImportRateThrottle(UserRateThrottle): scope='import'
class PublicVerificationRateThrottle(AnonRateThrottle): scope='public_verify'
class AIInsightRateThrottle(UserRateThrottle): scope='ai'
class SensitiveActionRateThrottle(UserRateThrottle): scope='sensitive_action'
